title:              Modellist
email:              modellist@gmail.com
description:        An educational blog in machine learning
author:             Pavel Ianko
baseurl:            ""
url:                "https://PashaIanko.github.io"

# Social Profiles
twitter_username:   
github_username:    PashaIanko
facebook_username:  
instagram_username: modellist.ml 
linkedin_username: pavelianko

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
